precision highp float;

// Droste / Escher spiral via complex log + exp.
//
// Reference: B. de Smit & H. W. Lenstra (2003), "The Mathematical Structure
// of Escher's Print Gallery", and 3Blue1Brown, "This picture broke my brain"
// (https://youtu.be/ldxFjLJ3rVY).
//
// For each output pixel z we take the complex log w = log(z) = (ln|z|, arg z)
// and apply the Escher map h(w) = w * alpha with
//   alpha = (log(scale) + 2*pi*i * twist) / (2*pi*i)
// which shears log-space so that "one full rotation" equals "one zoom level".
// Wrapping in the sheared direction produces a recursive image whose tile
// boundary is a SPIRAL (invisible when twist != 0) instead of a hard circle.

uniform sampler2D uTexture;
uniform vec2 uResolution;
uniform vec2 uGeometry;    // x = log(scale), y = twist (rotations per zoom)
uniform float uZoomSpeed;
uniform float uTime;
uniform float uTexAspect;
uniform float uShowGrid;

varying vec2 vUv;

#define PI 3.14159265359
#define TWO_PI 6.28318530718

vec2 cropToSquare(vec2 uv) {
  if (uTexAspect > 1.0) {
    float offset = (1.0 - 1.0 / uTexAspect) * 0.5;
    uv.x = uv.x / uTexAspect + offset;
  } else if (uTexAspect < 1.0) {
    float offset = (1.0 - uTexAspect) * 0.5;
    uv.y = uv.y * uTexAspect + offset;
  }
  return uv;
}

void main() {
  vec2 z = (vUv - 0.5) * 2.0;
  float r = length(z);

  if (r < 1e-5) {
    gl_FragColor = vec4(0.0);
    return;
  }

  // Zoom period in log-r. Larger |logScale| -> more visible levels.
  float logScale = uGeometry.x;
  // Twist: rotations performed per one zoom level. 0 = straight Droste
  // (a hard circular seam), 1 = classic Escher spiral (seam is a full
  // spiral turn and is hidden by angular continuity), non-integer = multi-arm.
  float twist = uGeometry.y;

  if (abs(logScale) < 1e-3) {
    gl_FragColor = texture2D(uTexture, cropToSquare(vUv));
    return;
  }

  // Complex log of z.
  vec2 w = vec2(log(r), atan(z.y, z.x));

  // Shear coordinates: a = how many zoom levels "up" we are,
  //                    b = angular position within that level.
  //
  // Lattice in (w.x, w.y) is generated by
  //   alpha = (logScale, 2*pi*twist)   (one zoom + twist turns)
  //   beta  = (0,        2*pi)          (one pure rotation; free from log branch)
  //
  // Solve  w = a*alpha + b*beta :
  //   a = w.x / logScale
  //   b = (w.y - a*2*pi*twist) / (2*pi)
  float a = w.x / logScale;
  float b = (w.y - a * TWO_PI * twist) / TWO_PI;

  // Animate the zoom along the alpha direction.
  a += uTime * uZoomSpeed;

  // Tile: wrap a into [0,1). With twist != 0 this wrap is a spiral in
  // output space, not a circle -- the "hard edge" becomes continuous
  // along the angular direction.
  a = fract(a);

  // Reconstruct w. Note b is NOT wrapped: exp is already 2*pi-periodic in
  // the imaginary part, so any integer shift of b by 2*pi leaves exp(w)
  // unchanged.
  w = vec2(a * logScale, a * TWO_PI * twist + b * TWO_PI);

  // exp back to the complex plane.
  vec2 finalZ = exp(w.x) * vec2(cos(w.y), sin(w.y));

  // Sample the webcam. We want the fundamental strip to cover the texture,
  // so map finalZ (which after fract lies in |z| in [1, exp(logScale)])
  // into [-1,1] by dividing out the scale factor.
  float norm = exp(max(logScale, 0.0));
  vec2 texUv = finalZ / norm * 0.5 + 0.5;
  texUv = cropToSquare(texUv);
  texUv = clamp(texUv, 0.0, 1.0);

  vec4 color = texture2D(uTexture, texUv);

  if (uShowGrid > 0.5) {
    // Grid drawn in the sheared (a, b) coordinate -- visualizes the warp.
    float gridFreq = 10.0;
    vec2 gridCoord = vec2(a, b) * gridFreq;
    vec2 gridLine = abs(fract(gridCoord - 0.5) - 0.5);
    float line = 1.0 - smoothstep(0.0, 0.06, min(gridLine.x, gridLine.y));

    vec2 gridCoord5 = vec2(a, b) * (gridFreq / 5.0);
    vec2 gridLine5 = abs(fract(gridCoord5 - 0.5) - 0.5);
    float majorLine = 1.0 - smoothstep(0.0, 0.04, min(gridLine5.x, gridLine5.y));

    vec3 gridColor = mix(vec3(0.0, 0.8, 1.0), vec3(1.0), majorLine);
    float gridAlpha = max(line * 0.5, majorLine * 0.8);
    color.rgb = mix(color.rgb, gridColor, gridAlpha);
  }

  gl_FragColor = color;
}
